### ISSUE TITLE
Hi I tried to run this but getting the following errors

### ISSUE THREAD

**Issue by GowsikChandran** [Tohure/GraphQLwithDaggerMVP_Java#1]
error: cannot find symbol class DaggerAppComponent

error: A @Module may not contain both non-static @Provides methods and abstract @Binds or @Multibinds declarations

error: dagger.internal.codegen.ComponentProcessor was unable to process this interface because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.

**Comment by tohure** [comment]
Sorry by delay, It was my error, in each provider, it's necessary to make each method of static type.
I don't know why I deleted that. Sorry I'm gonna fix it right now!

**Comment by tohure** [comment]
Ready, I fixed the error, please download the changes and check that everything is OK. Sorry for the inconvenience and thank you for your collaboration @gowsikreloaded !

**Comment by gowsikreloaded** [comment]
@Tohure  Thanks a lot :) 
and I am trying to test the below method in with Mockito but could not do that 
pls help

```
 public void searchQuery(@NonNull final String query, @Nullable String afterCursor,
                            @NonNull final GitGraphQlRepositoryCallback callback) {


        SearchRepoQuery searchRepoQuery = SearchRepoQuery.builder()
                .query(query)
                .afterCursor(afterCursor)
                .build();

        ApolloCall<SearchRepoQuery.Data> searchApolloCall =
         apolloClient.query(searchRepoQuery).responseFetcher(ApolloResponseFetchers.NETWORK_FIRST);

        searchApolloCall.enqueue(new ApolloCallback<>(new ApolloCall.Callback<SearchRepoQuery.Data() {
            @Override
            public void onResponse(@Nonnull Response<SearchRepoQuery.Data> response) {
                callback.handleGitHubResponse(response);
            }

            @Override
            public void onFailure(@Nonnull ApolloException e) {
                callback.handleGitHubError();
            }
        }, handler));
    }
```
